apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: grafana-cloud-from-kubernetes
spec:
  image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.157.0
  # mount the Secret's keys as environment variables in the collector container
  envFrom:
    - secretRef:
        name: grafana-cloud-credentials
  config:
    extensions:
      basicauth:
        client_auth:
          username: "${env:GRAFANA_CLOUD_USER}"
          password: "${env:GRAFANA_CLOUD_TOKEN}"

    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317

    exporters:
      otlp_http:
        endpoint: https://otlp-gateway-prod-eu-west-2.grafana.net/otlp
        auth:
          authenticator: basicauth

    service:
      extensions: [basicauth]
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [otlp_http]
        logs:
          receivers: [otlp]
          exporters: [otlp_http]
        metrics:
          receivers: [otlp]
          exporters: [otlp_http]
