apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: profiling-the-collector
spec:
  image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.154.0
  config:
    extensions:
      # exposes Go's net/http/pprof profiles (CPU, heap, goroutines, ...)
      pprof:
        endpoint: 0.0.0.0:1777

    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    exporters:
      nop: {}

    service:
      extensions: [pprof]
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [nop]
        logs:
          receivers: [otlp]
          exporters: [nop]
        metrics:
          receivers: [otlp]
          exporters: [nop]
