apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otelcol-loadbalancer
spec:
  image: ghcr.io/jpkrohling/otelcol-distributions/otelcol-loadbalancer:0.101.7
  replicas: 3
  config:
    receivers:
      otlp:
        protocols:
          grpc: {}

    exporters:
      loadbalancing:
        protocol:
          otlp:
            tls:
              insecure: true
        resolver:
          dns:
            hostname: otelcol-sampling-collector-headless

    service:
      extensions: [ ]
      pipelines:
        traces:
          receivers:  [ otlp ]
          processors: [  ]
          exporters:  [ loadbalancing ]
        logs:
          receivers:  [ otlp ]
          processors: [  ]
          exporters:  [ loadbalancing ]
        metrics:
          receivers:  [ otlp ]
          processors: [  ]
          exporters:  [ loadbalancing ]
      telemetry:
        metrics:
          level: detailed
          readers:
            - periodic:
                exporter:
                  otlp:
                    endpoint: https://otlp-gateway-prod-eu-west-2.grafana.net/otlp/v1/metrics
                    protocol: http/protobuf
                    headers:
                      Authorization: "Basic MTE3OTkzNTpnbGNfZXlKdklqb2lNVE0xTnpRMU1pSXNJbTRpT2lKemRHRmpheTB4TVRjNU9UTTFMVzkwYkhBdGQzSnBkR1V0YjNSc2NDSXNJbXNpT2lKMk16WnFNRFl6ZDFJeVNVZ3hZVFV6YkZwSWREUm5TbTRpTENKdElqcDdJbklpT2lKd2NtOWtMV1YxTFhkbGMzUXRNaUo5ZlE9PQ=="
        resource:
          "service.name": "otelcol-loadbalancer"
