apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otelcol-loadbalancer
spec:
  image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.126.0
  replicas: 3
  config:
    receivers:
      otlp:
        protocols:
          grpc: {}

    exporters:
      loadbalancing:
        protocol:
          otlp:
            tls:
              insecure: true
        resolver:
          dns:
            hostname: otelcol-sampling-collector-headless

    service:
      extensions: [ ]
      pipelines:
        traces:
          receivers:  [ otlp ]
          processors: [  ]
          exporters:  [ loadbalancing ]
        logs:
          receivers:  [ otlp ]
          processors: [  ]
          exporters:  [ loadbalancing ]
        metrics:
          receivers:  [ otlp ]
          processors: [  ]
          exporters:  [ loadbalancing ]
      telemetry:
        metrics:
          level: detailed
          readers:
            - periodic:
                exporter:
                  otlp:
                    endpoint: http://lgtm.lgtm.svc.cluster.local:4318/v1/metrics
                    protocol: http/protobuf
        resource:
          "service.name": "otelcol-loadbalancer"
