apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: cve-bomb
spec:
  image: ghcr.io/jpkrohling/otelcol-distributions/otelcol-otlp:0.101.5
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"

  config:
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}

    exporters:
      nop: {}

    service:
      extensions: [  ]
      pipelines:
        traces:
          receivers:  [ otlp ]
          processors: [  ]
          exporters:  [ nop ]
        logs:
          receivers:  [ otlp ]
          processors: [  ]
          exporters:  [ nop ]
        metrics:
          receivers:  [ otlp ]
          processors: [  ]
          exporters:  [ nop ]
      telemetry:  
        metrics:
          level: detailed
