apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: profiling-the-collector
spec:
  image: ghcr.io/jpkrohling/otelcol-distributions/otelcol-otlp:0.101.5
  config:
    extensions:
      pprof:
        endpoint: 0.0.0.0:1777

    receivers:
      otlp:
        protocols:
          grpc: {}

    exporters:
      nop: {}

    service:
      extensions: [ pprof ]
      pipelines:
        traces:
          receivers:  [ otlp ]
          processors: [  ]
          exporters:  [ nop ]
        logs:
          receivers:  [ otlp ]
          processors: [  ]
          exporters:  [ nop ]
        metrics:
          receivers:  [ otlp ]
          processors: [  ]
          exporters:  [ nop ]
