apiVersion: v1
kind: Pod
metadata:
  name: my-microservice
  annotations:
    sidecar.opentelemetry.io/inject: "otelcol-to-lgtm"
spec:
  containers:
  - name: my-microservice
    image: my-org/my-microservice:v0.0.0
    ports:
      - containerPort: 8080
        protocol: TCP
