apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-workload-service
  name: my-workload-service
spec:
  ports:
  - name: http-metrics
    port: 2112
    targetPort: metrics
    protocol: TCP
  selector:
    app: my-workload
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: target-allocator-recipe-metrics
spec:
  endpoints:
  - interval: 15s
    targetPort: 2112
    path: /metrics
  selector:
    matchLabels:
      app: my-workload-service
