apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otelcol-simple
spec:
  image: cr.olly.garden/ollygarden/tulip/tulip:0.0.1
  config:
    receivers:
      otlp:
        protocols:
          http: {}

    exporters:
      nop: {}

    service:
      pipelines:
        traces:
          receivers:  [ otlp ]
          processors: [  ]
          exporters:  [ nop ]
        logs:
          receivers:  [ otlp ]
          exporters:  [ nop ]

