apiVersion: apps/v1
kind: Deployment
metadata:
  name: lgtm
  labels:
    app: lgtm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lgtm
  template:
    metadata:
      labels:
        app: lgtm
    spec:
      containers:
      - name: lgtm
        image: grafana/otel-lgtm
        ports:
        - containerPort: 4317
          name: grpc-otlp
        - containerPort: 4318
          name: http-otlp
        - containerPort: 3000
          name: http-ui
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 1000m
            memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: lgtm
spec:
  selector:
    app: lgtm
  ports:
  - name: http-otlp
    port: 4318
    targetPort: http-otlp
  - name: grpc-otlp
    port: 4317
    targetPort: grpc-otlp
  - name: http-ui
    port: 3000
    targetPort: http-ui
  type: ClusterIP
